apiVersion: batch/v1
kind: Job
metadata:
  generateName: team-b-job-
  namespace: team-b
  labels:
    kueue.x-k8s.io/queue-name: team-b-lq
spec:
  parallelism: 3
  completions: 3
  suspend: true
  template:
    spec:
      containers:
      - name: batch-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.1.0
        args: ["60s"]
        resources:
          requests:
            cpu: "100m" # Total: 3 * 100m = 300m
            memory: "100Mi"
      restartPolicy: Never
